version: '2'
services:
    holley_ims-app:
        image: holley_ims
        external_links:
            - holley_ims-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/holley_ims?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    holley_ims-mysql:
        extends:
            file: mysql.yml
            service: holley_ims-mysql
