version: '2'
services:
    holley_ims-mysql:
        container_name: holley_ims-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/holley_ims/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=holley_ims
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
